"""
Pydantic models for API responses.
"""
from pydantic import BaseModel
from typing import List, Optional


class Alert(BaseModel):
    """Alert generated by backend."""
    severity: str
    message: str
    sensorValue: float


class SensorDataResponse(BaseModel):
    """Response from sensor data POST endpoint."""
    success: bool = True
    message: Optional[str] = None
    alertsGenerated: int = 0
    alerts: List[Alert] = []


class OutdoorAQIData(BaseModel):
    """Outdoor AQI data from backend."""
    aqi: Optional[int] = None
    pm25: Optional[float] = None
    pm10: Optional[float] = None
    no2: Optional[float] = None
    cityName: Optional[str] = None
